conpaas image creation script: first step to support Debian 7 Wheezy.

diff --git a/conpaas-services/scripts/create_vm/scripts/502-galera b/conpaas-services/scripts/create_vm/scripts/502-galera
--- a/conpaas-services/scripts/create_vm/scripts/502-galera
+++ b/conpaas-services/scripts/create_vm/scripts/502-galera
@@ -6,17 +6,83 @@ apt-get -f -y update
 DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes --no-install-recommends --no-upgrade install \
 		psmisc libaio1 libdbi-perl libdbd-mysql-perl mysql-client rsync python-mysqldb make
 
-wget https://launchpad.net/galera/2.x/23.2.4/+download/galera-23.2.4-amd64.deb 2>/dev/null
-dpkg -i galera-23.2.4-amd64.deb
+if [ $DEBIAN_DIST == "squeeze" ]
+then
+    cd /root/
+#    wget https://launchpad.net/galera/2.x/23.2.4/+download/galera-23.2.4-amd64.deb 2>/dev/null
+#    dpkg -i galera-23.2.4-amd64.deb
 
-wget https://launchpad.net/codership-mysql/5.5/5.5.29-23.7.3/+download/mysql-server-wsrep-5.5.29-23.7.3-amd64.deb 2>/dev/null
-dpkg -i mysql-server-wsrep-5.5.29-23.7.3-amd64.deb
+    wget https://launchpad.net/galera/2.x/25.2.8/+download/galera-25.2.8-$ARCH.deb 2>/dev/null
+    dpkg -i galera-25.2.8-$ARCH.deb
 
-wget http://www.codership.com/files/glb/glb-1.0.0rc1.tar.gz 2>/dev/null
-tar xvfz glb-1.0.0rc1.tar.gz
-cd glb-1.0.0rc1
+#    wget https://launchpad.net/codership-mysql/5.5/5.5.29-23.7.3/+download/mysql-server-wsrep-5.5.29-23.7.3-amd64.deb 2>/dev/null
+#    dpkg -i mysql-server-wsrep-5.5.29-23.7.3-amd64.deb
+
+    wget https://launchpad.net/codership-mysql/5.5/5.5.34-25.9/+download/mysql-server-wsrep-5.5.34-25.9-$ARCH.deb 2>/dev/null
+    dpkg -i mysql-server-wsrep-5.5.34-25.9-$ARCH.deb
+
+    rm -f mysql-server-wsrep-5.5.34-25.9-$ARCH.deb
+    rm -f galera-25.2.8-$ARCH.deb
+    
+    ## Fixing a bug in MySQL Galera (actually fixed in MySQL Galera 5.5.31-23.7.5 in June 2013)
+#    sed 's.>>/dev/stderr.>\&2.' /usr/bin/wsrep_sst_common
+
+elif [ $DEBIAN_DIST == "wheezy" ]
+then
+    cd /root/
+#    # Galera version 3.x
+#    wget https://launchpad.net/galera/3.x/25.3.1/+download/galera-25.3.1-$ARCH.deb 2>/dev/null
+#    dpkg -i galera-25.3.1-$ARCH.deb
+
+    # Pre-build package depends on libssl0.9.8 whereas wheezy ships with libssl1.0.0
+    # Building and installing from source to link with libssl1.0.0
+    DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes --no-install-recommends --no-upgrade install \
+        scons libssl-dev libboost-dev libboost-program-options-dev check
+    wget https://launchpad.net/galera/3.x/25.3.1/+download/galera-25.3.1-src.tar.gz 2> /dev/null
+    tar -xaf galera-25.3.1-src.tar.gz
+    cd galera-25.3.1-src
+    scons /
+    cd ..
+    rm -rf galera-25.3.1-src
+
+#    # Galera version 2.x
+#    DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes --no-install-recommends --no-upgrade install libssl0.9.8
+#    wget https://launchpad.net/galera/2.x/25.2.8/+download/galera-25.2.8-$ARCH.deb 2> /dev/null
+#    dpkg -i galera-25.2.8-$ARCH.deb
+    
+    wget https://launchpad.net/codership-mysql/5.5/5.5.34-25.9/+download/mysql-server-wsrep-5.5.34-25.9-$ARCH.deb 2>/dev/null
+    dpkg -i mysql-server-wsrep-5.5.34-25.9-$ARCH.deb
+
+    rm -f mysql-server-wsrep-5.5.34-25.9-$ARCH.deb
+    rm -f galera-25.3.1-src.tar.gz
+
+else
+    echo "ERROR: unknown Debian distribution '$DEBIAN_DIST': cannot select correct MySQL Galera packages."
+    exit 1
+fi
+
+
+# Added more wait time before deciding whether the mysql daemon has failed to start (idem for stopping)
+sed -i 's/1 2 3 4 5 6.*;/\$(seq 60);/' /etc/init.d/mysql
+
+
+# Install Galera Load Balancer (glb)
+
+glb_version=1.0.1
+wget http://www.codership.com/files/glb/glb-\${glb_version}.tar.gz 2>/dev/null
+tar xvfz glb-\${glb_version}.tar.gz
+cd glb-\${glb_version}
 ./configure; make; make install
+cp -a ./files/glbd.sh /etc/init.d/glbd
+cp -a ./files/glbd.cfg /etc/default/glbd
+# using default listen port 8010
+sed -i 's/#LISTEN_ADDR/LISTEN_ADDR/' /etc/default/glbd
+# using default listen port 8011
+## wait 1 second after EOF to close nc
+sed -i 's/#CONTROL_ADDR/CONTROL_ADDR/' /etc/default/glbd
+sed -i 's/nc \$CONTROL_IP/nc -q 1 \$CONTROL_IP/' /etc/init.d/glbd
 cd ..
-rm -fr glb-1.0.0rc1
+rm -fr glb-\${glb_version} glb-\${glb_version}.tar.gz
+
 
 EOF
diff --git a/conpaas-services/scripts/create_vm/scripts/503-condor b/conpaas-services/scripts/create_vm/scripts/503-condor
--- a/conpaas-services/scripts/create_vm/scripts/503-condor
+++ b/conpaas-services/scripts/create_vm/scripts/503-condor
@@ -13,7 +13,18 @@ wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
 # added [arch=amd64 trusted=yes] to avoid authentication warning
 echo "deb [arch=amd64 trusted=yes] http://research.cs.wisc.edu/htcondor/debian/stable/ $DEBIAN_DIST contrib" >> /etc/apt/sources.list
 apt-get update
-apt-get -f -y --force-yes install sun-java6-jdk ant condor sudo xvfb
+if [ $DEBIAN_DIST == "squeeze" ]
+then
+    DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes --no-install-recommends --no-upgrade \
+        install sun-java6-jdk ant condor sudo xvfb
+elif [ $DEBIAN_DIST == "wheezy" ]
+then
+    DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes --no-install-recommends --no-upgrade \
+        install openjdk-7-jre-headless ant condor sudo xvfb
+else
+    echo "Error: unknown Debian distribution '$DEBIAN_DIST': cannot select correct Condor packages."
+    exit 1
+fi
 
 # next 12 lines moved here from conpaas-services/scripts/manager/htc-manager-start
 apt-get update -y 
diff --git a/conpaas-services/scripts/create_vm/scripts/504-selenium b/conpaas-services/scripts/create_vm/scripts/504-selenium
--- a/conpaas-services/scripts/create_vm/scripts/504-selenium
+++ b/conpaas-services/scripts/create_vm/scripts/504-selenium
@@ -2,13 +2,24 @@
 
 cat <<EOF >> $ROOT_DIR/conpaas_install
 cecho "===== install SELENIUM ====="
-# recent versions of iceweasel and chrome
-echo "deb http://backports.debian.org/debian-backports $DEBIAN_DIST-backports main" >> /etc/apt/sources.list
-echo "deb http://mozilla.debian.net/ $DEBIAN_DIST-backports iceweasel-esr" >> /etc/apt/sources.list
-    
-apt-get -f -y update
-apt-get -f -y --force-yes install -t $DEBIAN_DIST-backports iceweasel
-apt-get -f -y --force-yes install xvfb xinit chromium-browser sun-java6-jdk
+
+if [ $DEBIAN_DIST == "squeeze" ]
+then
+    # recent versions of iceweasel and chrome
+    echo "deb http://backports.debian.org/debian-backports $DEBIAN_DIST-backports main" >> /etc/apt/sources.list
+    echo "deb http://mozilla.debian.net/ $DEBIAN_DIST-backports iceweasel-esr" >> /etc/apt/sources.list
+
+    apt-get -f -y update
+    apt-get -f -y --force-yes install -t $DEBIAN_DIST-backports iceweasel
+    apt-get -f -y --force-yes install xvfb xinit chromium-browser sun-java6-jdk
+elif [ $DEBIAN_DIST == "wheezy" ]
+then
+    apt-get -f -y update
+    apt-get -f -y --force-yes install iceweasel xvfb xinit chromium-browser openjdk-7-jre-headless
+else
+    echo "Error: unknown Debian distribution '$DEBIAN_DIST': cannot select correct Selenium packages."
+    exit 1
+fi
 
 EOF
 
diff --git a/conpaas-services/scripts/create_vm/scripts/507-xtreemfs b/conpaas-services/scripts/create_vm/scripts/507-xtreemfs
--- a/conpaas-services/scripts/create_vm/scripts/507-xtreemfs
+++ b/conpaas-services/scripts/create_vm/scripts/507-xtreemfs
@@ -3,15 +3,25 @@
 cat <<EOF >> $ROOT_DIR/conpaas_install
 cecho "===== install xtreemfs repo ====="
 # add xtreemfs repo
-echo "deb http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_6.0 /" >> /etc/apt/sources.list
-wget -O - http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_6.0/Release.key 2>/dev/null | apt-key add -
+if [ "$DEBIAN_DIST" == "squeeze" ]
+then
+    echo "deb http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_6.0 /" >> /etc/apt/sources.list
+    wget -O - http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_6.0/Release.key 2>/dev/null | apt-key add -
+elif [ "$DEBIAN_DIST" == "wheezy" ]
+then
+    echo "deb http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_7.0 /" >> /etc/apt/sources.list
+    wget -O - http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_7.0/Release.key 2>/dev/null | apt-key add -
+else
+    echo "ERROR: unknown Debian distribution '$DEBIAN_DIST'."
+    exit 1
+fi
 apt-get -f -y update
 apt-get -f -y --no-install-recommends --no-upgrade install xtreemfs-server xtreemfs-client xtreemfs-tools
 update-rc.d xtreemfs-osd disable
 update-rc.d xtreemfs-mrc disable
 update-rc.d xtreemfs-dir disable
 # remove xtreemfs repo
-sed --in-place 's%deb http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_6.0 /%%' /etc/apt/sources.list
+sed --in-place 's%deb http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/Debian_..0 /%%' /etc/apt/sources.list
 apt-get -f -y update
 
 EOF
