php: updated to work on a Debian 8 image
- updated the configuration files to be compatible with Debian 8
- php needs scalaris to store session data, so I modified the image creation script to automatically install the scalaris binaries if the php service is selected
- updated the image creation script with the correct repository for scalaris in Debian 8
- updated the scalaris parameters to be compatible with the new version
- updated the PHP version in the add service page

diff --git a/conpaas-services/scripts/create_vm/scripts/506-scalaris b/conpaas-services/scripts/create_vm/scripts/506-scalaris
--- a/conpaas-services/scripts/create_vm/scripts/506-scalaris
+++ b/conpaas-services/scripts/create_vm/scripts/506-scalaris
@@ -3,13 +3,27 @@
 cat <<EOF >> $ROOT_DIR/conpaas_install
 cecho "===== install scalaris repo ====="
 # add scalaris repo
-echo "deb http://download.opensuse.org/repositories/home:/scalaris/Debian_6.0 /" >> /etc/apt/sources.list
-wget -O - http://download.opensuse.org/repositories/home:/scalaris/Debian_6.0/Release.key 2>/dev/null | apt-key add -
+if [ "$DEBIAN_DIST" == "squeeze" ]
+then
+    echo "deb http://download.opensuse.org/repositories/home:/scalaris/Debian_6.0 /" >> /etc/apt/sources.list
+    wget -O - http://download.opensuse.org/repositories/home:/scalaris/Debian_6.0/Release.key 2>/dev/null | apt-key add -
+elif [ "$DEBIAN_DIST" == "wheezy" ]
+then
+    echo "deb http://download.opensuse.org/repositories/home:/scalaris/Debian_7.0 /" >> /etc/apt/sources.list
+    wget -O - http://download.opensuse.org/repositories/home:/scalaris/Debian_7.0/Release.key 2>/dev/null | apt-key add -
+elif [ "$DEBIAN_DIST" == "jessie" ]
+then
+    echo "deb http://download.opensuse.org/repositories/home:/scalaris/Debian_8.0 /" >> /etc/apt/sources.list
+    wget -O - http://download.opensuse.org/repositories/home:/scalaris/Debian_8.0/Release.key 2>/dev/null | apt-key add -
+else
+    echo "ERROR: unknown Debian distribution '$DEBIAN_DIST'."
+    exit 1
+fi
 apt-get -y update
 apt-get -f -y --no-install-recommends --no-upgrade install scalaris screen erlang
 update-rc.d scalaris disable
 # remove scalaris repo
-sed --in-place 's%deb http://download.opensuse.org/repositories/home:/scalaris/Debian_6.0 /%%' /etc/apt/sources.list
+sed --in-place 's%deb http://download.opensuse.org/repositories/home:/scalaris/Debian_..0 /%%' /etc/apt/sources.list
 apt-get -y update
 
 EOF
