Improvements to the VM creation script from Emanuele Rocca

diff --git a/web-servers/scripts/opennebula-create-new-vm-image b/web-servers/scripts/opennebula-create-new-vm-image
--- a/web-servers/scripts/opennebula-create-new-vm-image
+++ b/web-servers/scripts/opennebula-create-new-vm-image
@@ -18,6 +18,7 @@ FILESIZE=2048 #MB
 
 # The Debian distribution that you would like to have installed (we recommend squeeze).
 DEBIAN_DIST=squeeze
+DEBIAN_MIRROR=http://ftp.nl.debian.org/debian
 
 # The architecture and kernel version for the OS that will be installed (please make
 # sure to modify the kernel version name accordingly if you modify the architecture).
@@ -37,6 +38,50 @@ if [ `id -u` -ne 0 ]; then
   cecho 'need root permissions for this script';
   exit 1;
 fi
+
+# System rollback function
+function cleanup() {
+    # Set errormsg if something went wrong
+    [ $? -ne 0 ] && errormsg="Script terminated with errors"
+
+    for mpoint in /dev /proc /
+    do
+      mpoint="${ROOT_DIR?:not set}${mpoint}"
+
+      # Only attempt to umount $ROOT_DIR{/dev,/proc,/} if necessary
+      if [ -d $mpoint ]
+      then
+        cecho "Umounting $mpoint"
+        umount $mpoint || true
+      fi
+    done
+
+    sleep 1s
+    losetup -d $LOOP_DEV_P
+    sleep 1s
+    kpartx -d $LOOP_DEV
+    sleep 1s
+    losetup -d $LOOP_DEV
+    sleep 1s
+    rm -r $ROOT_DIR
+    # Print "Done" on success, $errormsg otherwise
+    cecho "${errormsg:-Done}"
+}
+
+# Check if required binaries are in $PATH
+for bin in dd parted losetup kpartx mkfs.ext3 tune2fs mount debootstrap chroot umount grub-install
+do
+  if [ -z `which $bin` ]
+  then
+    if [ -x /usr/lib/command-not-found ]
+    then
+      /usr/lib/command-not-found $bin
+    else
+      echo "$bin: command not found"
+    fi
+    exit 1
+  fi
+done
 
 cecho "Creating empty disk image at" $FILENAME
 dd if=/dev/zero of=$FILENAME bs=1M count=$FILESIZE
@@ -76,8 +121,11 @@ losetup $LOOP_DEV_P $PART_DEV
 mount $LOOP_DEV_P $ROOT_DIR
 #mount $PART_DEV $ROOT_DIR
 
+# Always clean up on exit
+trap "cleanup" EXIT
+
 cecho "Starting debootstrap"
-debootstrap --arch $ARCH $DEBIAN_DIST $ROOT_DIR
+debootstrap --arch $ARCH $DEBIAN_DIST $ROOT_DIR $DEBIAN_MIRROR
 
 cecho "Writing fstab"
 echo "/dev/sda1 / ext3 defaults 0 1" > $ROOT_DIR/etc/fstab
@@ -232,22 +280,6 @@ umount /mnt
 exit 0
 EOF
 
-#########################
-
-cecho "Umounting dev and proc"
-umount $ROOT_DIR/dev
-umount $ROOT_DIR/proc
-sleep 1s
-cecho "Umounting $ROOT_DIR"
-umount $ROOT_DIR
-sleep 1s
-losetup -d $LOOP_DEV_P
-kpartx -d $LOOP_DEV
-sleep 1s
-losetup -d $LOOP_DEV
-sleep 1s
-rm -r $ROOT_DIR
-cecho "Done"
 
 
 
